services:
  transmission:
    container_name: transmission
    environment:
      - PUID=${PUID_DOCKUSER}
      - PGID=${PGID_APPZ}
      - USER=${TRANSMISSION_USERNAME}
      - PASS=${TRANSMISSION_PASS}
    image: linuxserver/transmission
    network_mode: 'host'
    hostname: 'transmission'
    volumes:
      - ${CONFIG}/transmission:/config
      - ${DATA}:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp

  telegram-transmission-bot:
    container_name: telegram-transmission-bot
    restart: on-failure
    depends_on:
      - transmission
    network_mode: 'host'
    #image: kevinhalpin/transmission-telegram:latest
    build:
      dockerfile: Dockerfile
    image: result/latest
    command: '-token=${TELEGRAM_TRANSMISSION_BOT} -master=${TELEGRAM_USERNAME} -url=${TRANSMISSION_URL} -username=${TRANSMISSION_USERNAME} -password=${TRANSMISSION_PASS}'

